import pandas as pd
import sqlite3

# This script was generated by ChatGPT 4o (stawberry), with strict guidance and revie and amendment by myself, Olivier Butler

# Function to import CSV with specific event_name
def import_csv(file_path, event_name):
    # Read the CSV, skipping the first row
    df = pd.read_csv(file_path, skiprows=1)
    
    # Rename columns for clarity and drop unneeded columns
    df = df.rename(columns={'Date': 'timestamp', 'Observed': 'observed', 'Sum': 'sum'})
    df = df[['timestamp', 'observed', 'sum']]  # Keep only relevant columns
    
    # Replace '--' in observed and sum with 0
    df['observed'] = df['observed'].replace('--', 0).astype(int)
    df['sum'] = df['sum'].replace('--', 0).astype(int)
    
    # Convert timestamp column to datetime
    df['timestamp'] = pd.to_datetime(df['timestamp'], format='%m/%d/%Y %I:%M:%S %p')
    
    # Add a new column for the event name
    df['event_name'] = event_name

    # Connect to the SQLite database (create if not exists)
    conn = sqlite3.connect('debug_logs.db')
    
    # Create a table with required structure if it doesn't exist
    create_table_query = '''
    CREATE TABLE IF NOT EXISTS logs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        timestamp DATETIME,
        observed INTEGER,
        sum INTEGER,
        event_name TEXT
    )
    '''
    conn.execute(create_table_query)

    # Append the DataFrame to the SQLite table
    df.to_sql('logs', conn, if_exists='append', index=False)
    
    # Close the connection
    conn.close()
    print(f"Data from {file_path} imported successfully as '{event_name}'.")